metadata.format.version = "1.1"

[versions]

# Libraries
netty = "4.2.0.Final"
gson = "2.11.0"
guava = "33.3.1-jre"

velocity = "3.4.0-SNAPSHOT"
bungeecord = "1.21-R0.3-SNAPSHOT"

packetevents = "2.7.0"
protocolize = "2.4.1"
vpacketevents = "1.1.0"

adventure = "4.20.0"

# Plugins
blossom = "1.3.0"
shadow = "8.3.5"


[libraries]

netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
netty-transport = { module = "io.netty:netty-transport", version.ref = "netty" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
velocity-proxy = { module = "com.velocitypowered:velocity-proxy", version.ref = "velocity" }

bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord" }
bungeecord-protocol = { module = "net.md-5:bungeecord-protocol", version.ref = "bungeecord" }
bungeecord-proxy = { module = "net.md-5:bungeecord-proxy", version.ref = "bungeecord" }

packetevents-api = { module = "com.github.retrooper:packetevents-api", version.ref = "packetevents" }
packetevents-bungeecord = { module = "com.github.retrooper:packetevents-bungeecord", version.ref = "packetevents" }
packetevents-velocity = { module = "com.github.retrooper:packetevents-velocity", version.ref = "packetevents" }

protocolize-api = { module = "dev.simplix:protocolize-api", version.ref = "protocolize" }
protocolize-bungeecord = { module = "dev.simplix:protocolize-bungeecord", version.ref = "protocolize" }
protocolize-velocity = { module = "dev.simplix:protocolize-velocity", version.ref = "protocolize" }

vpacketevents-api = { module = "io.github.4drian3d:vpacketevents-api", version.ref = "vpacketevents" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }